### PR TITLE
Improved local development experience

### PR DESCRIPTION
**Pull request by l0g1x**

### CODE REVIEW

**Comment by l0g1x** [comment]
image


the return value below should technically be a User object being returned, however i get a console log error when returning a User object:

image

**Comment by dillionverma** [comment]
Addresses issues https://github.com/dillionverma/llm.report/issues/12 https://github.com/dillionverma/llm.report/issues/11

**Review by naveennaidu — APPROVED** [review]
Tested the branch locally and everything works.
It makes the setup process easy now.

**Comment by naveennaidu** [comment]
Great PR 🙌 @l0g1x

**Review by dillionverma — APPROVED** [review]
LGTM 🔥

thanks for this!!

**Pull request merged**
